FROM node:18-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy service source
COPY product-service ./product-service
WORKDIR /app/product-service

EXPOSE 4002
CMD ["node", "index.js"]
