FROM node:18-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy service source
COPY payment-service ./payment-service

# Set working directory to the service folder
WORKDIR /app/payment-service

EXPOSE 4004
CMD ["node", "index.js"]
