FROM node:18-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy service source
COPY inventory-service ./inventory-service

# Set working directory to the service folder
WORKDIR /app/inventory-service

EXPOSE 4005
CMD ["node", "index.js"]
